package orm;

/**
 * TLiuyan generated by MyEclipse Persistence Tools
 */

public class TLiuyan implements java.io.Serializable
{

	private String id;
	private String jineng_id;
	private String neirong;
	private String xingming;
	
	private String dianhua;
	private String liuyanshi;
	private String huifu;
	private Integer to_user_id;
	
	private Integer from_user_id;
	
	private Tuser fromUser;
	private Tuser toUser;
	private Trenwu jineng;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getNeirong() {
		return neirong;
	}
	public void setNeirong(String neirong) {
		this.neirong = neirong;
	}
	public String getXingming() {
		return xingming;
	}
	public void setXingming(String xingming) {
		this.xingming = xingming;
	}
	public String getDianhua() {
		return dianhua;
	}
	public void setDianhua(String dianhua) {
		this.dianhua = dianhua;
	}
	public String getLiuyanshi() {
		return liuyanshi;
	}
	
	public Tuser getFromUser() {
		return fromUser;
	}
	public void setFromUser(Tuser fromUser) {
		this.fromUser = fromUser;
	}
	public Tuser getToUser() {
		return toUser;
	}
	public void setToUser(Tuser toUser) {
		this.toUser = toUser;
	}
	public void setLiuyanshi(String liuyanshi) {
		this.liuyanshi = liuyanshi;
	}
	
	public String getHuifu() {
		return huifu;
	}
	public void setHuifu(String huifu) {
		this.huifu = huifu;
	}
	public Integer getTo_user_id() {
		return to_user_id;
	}
	public void setTo_user_id(Integer to_user_id) {
		this.to_user_id = to_user_id;
	}
	public Integer getFrom_user_id() {
		return from_user_id;
	}
	public void setFrom_user_id(Integer from_user_id) {
		this.from_user_id = from_user_id;
	}
	public String getJineng_id() {
		return jineng_id;
	}
	public void setJineng_id(String jineng_id) {
		this.jineng_id = jineng_id;
	}
	public Trenwu getJineng() {
		return jineng;
	}
	public void setJineng(Trenwu jineng) {
		this.jineng = jineng;
	}

}